vich_uploader:
    db_driver: orm

    mappings:
        avatar:
            uri_prefix: /avatar
            upload_destination: '%kernel.project_dir%/public/ressources/images/avatar'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true